### ISSUE TITLE
How to invoke HoverFast on command line

### ISSUE THREAD

**Issue by roberts10** [choosehappy/HoverFast#3]
How do I invoke HoverFast from the command line?  The documentation says to use the command, "HoverFast" followed by options.  Like:  

HoverFast --version

However, HoverFast isn't a command on my $PATH.

For context, I didn't have Docker available.  So installed like:

git clone https://github.com/choosehappy/HoverFast.git
cd HoverFast
pip install .

Thanks so much!  It's looks like a really amazing tool.

**Comment by petroslk** [comment]
Hey there!

Happy to see you're using HoverFast. Could you provide me with some information on the Operating System you are using and how you installed the tool? Was is done through conda or did you install it directly on the machine?

With this info I should be able to guide you a bit better and tell you exactly how to run it successfully!

Cheers,

Petros

**Comment by roberts10** [comment]
Installing in my /home directory of an HPC, which is Linux Red Hat 8. It doesn't have conda (or miniconda).  And I don't have Docker permissions. 

I created a python virtual environment with python 3.11.  Then I ran:

git clone https://github.com/choosehappy/HoverFast.git
cd HoverFast
pip install .

If Docker or Conda is required, I'm sure I could get my sys admin to install with those. 

Thanks!

**Comment by petroslk** [comment]
Thanks for the details! It sounds like the `HoverFast` command might not be recognized because the entry point script wasn’t added to your `$PATH` when you installed it.

Here’s how you can try to resolve this:

1. **Ensure the installation was successful:**  
   After running `pip install .`, you should see that the installation completed without errors. You can verify this by listing the installed packages in your virtual environment with `pip list` and checking for `HoverFast`.

2. **Check the Scripts Directory:**
   The `HoverFast` command is likely installed in the `Scripts` or `bin` directory of your virtual environment. You can find it by navigating to the `bin` directory in your virtual environment:
   
   ```bash
   cd /path/to/your/virtualenv/bin
   ls
   ```

3. **Add the Script to Your PATH:**
   If the `HoverFast` command is present in the `bin` directory but not recognized globally, you can add the directory to your `$PATH` temporarily:
   
   ```bash
   export PATH=/path/to/your/virtualenv/bin:$PATH
   ```
   After this, you should be able to run `HoverFast` directly from the command line.

Now, you should be able to invoke `HoverFast` using the command you mentioned, like `HoverFast --version`.

Keep in mind, for HPC environments, singularity (apptainer) might be more suitable since it does not require the same level of priviliges, so that might also be worth a try!

Let me know if this helps or if you run into any other issues!

Cheers,  
Petros

**Comment by roberts10** [comment]
That worked great

Just had to add the virtual env's /bin to my $PATH, like you said. 

Thanks again
